export const INGREDIENTS=['두부','달걀','우유','요거트','치즈','대파','양파','당근','감자','애호박','버섯','시금치','양배추','토마토','오이','김치','밥','면','참치','기타'];
export function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function validDate(value){if(!/^20\d{2}-\d{2}-\d{2}$/.test(value))return false;const [y,m,d]=value.split('-').map(Number),date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d;}
export function daysLeft(date,base=today()){return validDate(date)?Math.round((Date.parse(date+'T00:00:00Z')-Date.parse(base+'T00:00:00Z'))/86400000):null;}
const ENGLISH_INGREDIENTS=[['두부',/\btofu\b/i],['달걀',/\beggs?\b/i],['우유',/\bmilk\b/i],['요거트',/\byogh?urt\b/i],['치즈',/\bcheese\b/i],['대파',/\b(?:green onions?|spring onions?|scallions?)\b/i],['양파',/\bonions?\b/i],['당근',/\bcarrots?\b/i],['감자',/\bpotato(?:es)?\b/i],['애호박',/\b(?:zucchini|courgette)\b/i],['버섯',/\bmushrooms?\b/i],['시금치',/\bspinach\b/i],['양배추',/\bcabbage\b/i],['토마토',/\btomato(?:es)?\b/i],['오이',/\bcucumbers?\b/i],['김치',/\bkimchi\b/i],['밥',/\brice\b/i],['면',/\b(?:noodles?|pasta)\b/i],['참치',/\btuna\b/i]];
export function inferIngredient(name){return INGREDIENTS.slice(0,-1).find(x=>name.includes(x))||(name.includes('계란')?'달걀':ENGLISH_INGREDIENTS.find(([,pattern])=>pattern.test(name))?.[0]||'기타');}
export {extractDates} from './dates.mjs';
export function normalizeItem(raw){if(!raw||typeof raw.name!=='string'||!raw.name.trim()||raw.name.length>50)throw Error('재료 이름을 1~50자로 입력해 주세요.');const quantity=Number(raw.quantity);if(!Number.isFinite(quantity)||quantity<=0||quantity>9999)throw Error('수량은 0보다 크고 9,999 이하여야 해요.');if(raw.date&&!validDate(raw.date))throw Error('날짜를 확인해 주세요.');if(raw.date&&raw.verified!==true)throw Error('포장지의 날짜를 확인해 주세요.');return {id:typeof raw.id==='string'?raw.id.slice(0,80):crypto.randomUUID(),name:raw.name.trim(),ingredient:INGREDIENTS.includes(raw.ingredient)?raw.ingredient:inferIngredient(raw.name),quantity,unit:['개','팩','봉','g','ml','단'].includes(raw.unit)?raw.unit:'개',place:['냉장','냉동','실온'].includes(raw.place)?raw.place:'냉장',date:raw.date||'',dateKind:['useby','sellby','unknown'].includes(raw.dateKind)?raw.dateKind:'unknown',verified:!!raw.date&&raw.verified===true,opened:raw.opened===true,note:typeof raw.note==='string'?raw.note.slice(0,150):'',demo:raw.demo===true};}
export function readBackup(raw){const data=JSON.parse(raw);if(data?.format!=='hankan-v1'||!Array.isArray(data.items)||data.items.length>100)throw Error('한칸 백업 파일인지 확인해 주세요.');const ids=new Set();return data.items.map(x=>{if(typeof x?.id!=='string'||!x.id.trim()||x.id.length>80)throw Error('백업의 기록 번호를 확인해 주세요.');const item=normalizeItem(x);if(ids.has(item.id))throw Error('백업에 중복 기록이 있어요.');ids.add(item.id);return item;});}
export const RECIPES=[
 {id:'tofu',amounts:'두부 150g · 달걀 1개',title:'두부 달걀 부침',subtitle:'노릇하게 부쳐 가볍게 한 끼',ingredients:['두부','달걀'],basics:'식용유 1큰술, 소금 한 꼬집',minutes:15,icon:'tofu',steps:['두부는 도톰하게 썰어 물기를 닦아요.','달걀을 풀고 소금을 조금 넣어요.','두부에 달걀물을 입혀 기름을 두른 팬에서 양면을 익혀요. 달걀이 충분히 익었는지 확인해요.']},
 {id:'friedrice',amounts:'밥 1공기(200g) · 당근 30g · 양파 1/4개 · 달걀 1개',title:'냉장고 채소 볶음밥',subtitle:'조금씩 남은 채소를 한 팬에',ingredients:['밥','당근','양파','달걀'],basics:'식용유 1큰술, 간장 1작은술',minutes:20,icon:'carrot',steps:['당근과 양파를 잘게 썰어요.','팬에 기름을 두르고 채소가 부드러워질 때까지 볶아요.','달걀을 넣어 충분히 익힌 뒤 밥을 넣고 골고루 볶아요. 간장으로 간해요.']},
 {id:'zucchini',amounts:'애호박 1/2개 · 버섯 80g · 대파 10cm',title:'애호박 버섯 볶음',subtitle:'남은 재료로 만드는 간단한 반찬',ingredients:['애호박','버섯','대파'],basics:'식용유 1큰술, 소금 한 꼬집, 다진 마늘 1/2작은술',minutes:15,icon:'leaf',steps:['애호박과 버섯을 비슷한 크기로 썰고 대파를 송송 썰어요.','팬에 기름과 마늘을 넣고 볶다가 애호박을 넣어요.','버섯과 대파를 넣어 충분히 익히고 소금으로 간해요.']},
 {id:'potato',amounts:'감자 1개(150g) · 치즈 1장 · 우유 2큰술',title:'감자 치즈 팬구이',subtitle:'포슬포슬 감자와 고소한 치즈',ingredients:['감자','치즈','우유'],basics:'소금과 후추 조금',minutes:25,icon:'milk',steps:['감자를 작게 잘라 속까지 부드럽게 삶아요.','물을 빼고 감자를 으깬 뒤 우유를 조금씩 넣어 농도를 맞춰요.','팬에 펴고 치즈를 올려 약한 불에서 뚜껑을 덮고 치즈가 녹을 때까지 익혀요.']},
 {id:'kimchi',amounts:'김치 100g · 두부 150g · 양파 1/4개',title:'김치 두부 볶음',subtitle:'익숙한 재료로 든든하게',ingredients:['김치','두부','양파'],basics:'식용유 1/2큰술, 참기름 1/2작은술',minutes:20,icon:'tofu',steps:['두부는 먹기 좋게 썰어 데워요.','김치와 양파를 잘라 기름을 두른 팬에서 볶아요.','채소가 익으면 참기름을 조금 넣고 데운 두부와 함께 담아요.']},
 {id:'tomato',amounts:'토마토 1개 · 달걀 2개 · 대파 10cm',title:'토마토 달걀 볶음',subtitle:'촉촉하고 부드러운 한 접시',ingredients:['토마토','달걀','대파'],basics:'식용유 1큰술, 소금 한 꼬집',minutes:15,icon:'tomato',steps:['토마토와 대파를 썰고 달걀을 풀어요.','기름을 두른 팬에서 달걀을 충분히 익혀 잠시 덜어둬요.','토마토와 대파를 볶아 부드러워지면 달걀을 다시 넣고 소금으로 간해요.']}
];
export function recommend(items,base=today(),includeAll=false){const usable=items.filter(x=>daysLeft(x.date,base)!==null&&daysLeft(x.date,base)>=0&&x.verified),available=new Set(usable.map(x=>x.ingredient));return RECIPES.map(r=>{const have=r.ingredients.filter(x=>available.has(x)),missing=r.ingredients.filter(x=>!available.has(x)),urgent=have.filter(x=>usable.some(i=>i.ingredient===x&&daysLeft(i.date,base)<=3));return {...r,have,missing,urgent,score:have.length/r.ingredients.length*10+urgent.length*.5};}).filter(r=>includeAll||r.have.length).sort((a,b)=>b.score-a.score);}
