import {RECIPES} from './recipes.mjs';
export const INGREDIENTS=['두부','달걀','우유','요거트','치즈','대파','양파','당근','감자','애호박','버섯','시금치','양배추','토마토','오이','김치','밥','면','참치','기타'];
export function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function validDate(value){if(!/^20\d{2}-\d{2}-\d{2}$/.test(value))return false;const [y,m,d]=value.split('-').map(Number),date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d;}
export function daysLeft(date,base=today()){return validDate(date)?Math.round((Date.parse(date+'T00:00:00Z')-Date.parse(base+'T00:00:00Z'))/86400000):null;}
const ENGLISH_INGREDIENTS=[['두부',/\btofu\b/i],['달걀',/\beggs?\b/i],['우유',/\bmilk\b/i],['요거트',/\byogh?urt\b/i],['치즈',/\bcheese\b/i],['대파',/\b(?:green onions?|spring onions?|scallions?)\b/i],['양파',/\bonions?\b/i],['당근',/\bcarrots?\b/i],['감자',/\bpotato(?:es)?\b/i],['애호박',/\b(?:zucchini|courgette)\b/i],['버섯',/\bmushrooms?\b/i],['시금치',/\bspinach\b/i],['양배추',/\bcabbage\b/i],['토마토',/\btomato(?:es)?\b/i],['오이',/\bcucumbers?\b/i],['김치',/\bkimchi\b/i],['밥',/\brice\b/i],['면',/\b(?:noodles?|pasta)\b/i],['참치',/\btuna\b/i]];
export function inferIngredient(name){return INGREDIENTS.slice(0,-1).find(x=>name.includes(x))||(name.includes('계란')?'달걀':ENGLISH_INGREDIENTS.find(([,pattern])=>pattern.test(name))?.[0]||'기타');}
export {extractDates} from './dates.mjs';
export function normalizeItem(raw){if(!raw||typeof raw.name!=='string'||!raw.name.trim()||raw.name.length>50)throw Error('재료 이름을 1~50자로 입력해 주세요.');const quantity=Number(raw.quantity);if(!Number.isFinite(quantity)||quantity<=0||quantity>9999)throw Error('수량은 0보다 크고 9,999 이하여야 해요.');if(raw.date&&!validDate(raw.date))throw Error('날짜를 확인해 주세요.');if(raw.date&&raw.verified!==true)throw Error('포장지의 날짜를 확인해 주세요.');return {id:typeof raw.id==='string'?raw.id.slice(0,80):crypto.randomUUID(),name:raw.name.trim(),ingredient:INGREDIENTS.includes(raw.ingredient)?raw.ingredient:inferIngredient(raw.name),quantity,unit:['개','팩','봉','g','ml','단'].includes(raw.unit)?raw.unit:'개',place:['냉장','냉동','실온'].includes(raw.place)?raw.place:'냉장',date:raw.date||'',dateKind:['useby','sellby','unknown'].includes(raw.dateKind)?raw.dateKind:'unknown',verified:!!raw.date&&raw.verified===true,opened:raw.opened===true,note:typeof raw.note==='string'?raw.note.slice(0,150):'',demo:raw.demo===true};}
export function readBackup(raw){const data=JSON.parse(raw);if(data?.format!=='hankan-v1'||!Array.isArray(data.items)||data.items.length>100)throw Error('한칸 백업 파일인지 확인해 주세요.');const ids=new Set();return data.items.map(x=>{if(typeof x?.id!=='string'||!x.id.trim()||x.id.length>80)throw Error('백업의 기록 번호를 확인해 주세요.');const item=normalizeItem(x);if(ids.has(item.id))throw Error('백업에 중복 기록이 있어요.');ids.add(item.id);return item;});}
export {RECIPES} from './recipes.mjs';
export function recommend(items,base=today(),includeAll=false){const usable=items.filter(x=>daysLeft(x.date,base)!==null&&daysLeft(x.date,base)>=0&&x.verified),available=new Set(usable.map(x=>x.ingredient));return RECIPES.map(r=>{const have=r.ingredients.filter(x=>available.has(x)),missing=r.ingredients.filter(x=>!available.has(x)),urgent=have.filter(x=>usable.some(i=>i.ingredient===x&&daysLeft(i.date,base)<=3));return {...r,have,missing,urgent,score:have.length/r.ingredients.length*10+urgent.length*.5};}).filter(r=>includeAll||r.have.length).sort((a,b)=>b.score-a.score);}
